apiVersion: v1
kind: Pod
metadata:
  name: web-app01
  labels:
    app: web-app
spec:
  containers:
    - name: web-app
      image: nginx:alpine
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      resources:
        requests:
          cpu: "250m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"

---
apiVersion: v1
kind: Pod
metadata:
  name: web-app02
  labels:
    app: web-app
spec:
  containers:
    - name: web-app
      image: nginx:alpine
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      resources:
        requests:
          cpu: "250m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"