---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"
          requests:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        envFrom:
        - secretRef:
            name: nginx-secret
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config-map



---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
data:
  nginx.conf: |
      events {
        worker_connections  1024;
      }

      http {
        server {
        listen 80;
        server_name localhost;

          location / {
            add_header Content-Type 'application/json';

            return 200 '{"greeting": "Hi", "status": "ok"}';
          }
        }
      }


---
apiVersion: v1
kind: Secret
metadata: 
  name: nginx-secret
data:
  admin: bW9hYmRlbGF6ZW0K

--- 
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    # (default range: 30000–32767)
    nodePort: 30009
