# This is Simple Yaml File For Creating a Pod
# This is a simple pod definition file that creates a pod named web-server with a single container running the nginx:1.14.2 image. The container listens on port 80 for incoming traffic.
# The pod is created in the default namespace.

apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  containers:
  - name: web-server
    image: nginx:1.14.2
    ports:
    - containerPort: 80
      name: http
      protocol: TCP 
  