apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
data:
  database.url: "jdbc:mysql://db.example.com:3306/mydatabase"
  api.key: "12345-abcde-67890-fghij"

  app.props: |
    {
      "name": "MyApp",
      "version": "1.0.0",
      "description": "This is a sample application configuration."
    }
  
  config.props: |
    log_level=DEBUG
    retries=3