apiVersion: v1
kind: Pod
metadata: 
  name: config-map-pod
spec:
  containers:
    - name: config-map-container
      image: nginx:1.25
      resources:
        requests:
          cpu: "10m"
          memory: "250Mi"
        limits:
          cpu: "15m"
          memory: "500Mi"
      
      env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: myapp-config
              key: database.url

        - name: API_KEY
          valueFrom:
            configMapKeyRef:
              name: myapp-config
              key: api.key

      # We Can Expose All key-value pairs from config map
      # envFrom:
      #   - configMapRef:
      #       name: myapp-config
        